In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

## Creating a Tensor

In [ ]:
#using empty
a = torch.empty(2,3)
a

tensor([[1.5877e-42, 4.5539e-41, 0.0000e+00],
        [0.0000e+00, 1.8217e-44, 4.5539e-41]])

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.0315, 0.3926, 0.9578],
        [0.7285, 0.0455, 0.8500]])

In [ ]:
#use of seed
torch.seed()
torch.rand(2,3)

tensor([[0.2828, 0.0834, 0.6717],
        [0.6435, 0.7240, 0.2941]])

In [ ]:
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

#arange
print("using arange -->",torch.arange(0,10,2))
print("\n")
#using linspace
print("using linspace -->", torch.linspace(0,10,10))
print("\n")
#using eye
print("using eye -->",torch.eye(5))
print("\n")
#using full
print("using full -->",torch.full((3,3),5))

using arange --> tensor([0, 2, 4, 6, 8])


using linspace --> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


using eye --> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


using full --> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3976788629151364151]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.0777, 0.8889, 0.8205],
        [0.6304, 0.3197, 0.8847]])

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,3)
x

tensor([[0.3377, 0.9241, 0.6973],
        [0.4802, 0.0216, 0.5332]])

In [ ]:
# addition
print(f"addition : {x + 2}")
print("\n")

# substraction
print(f"Substraction :  {x - 2}")
print("\n")

# multiplication
print(f"Multiplication :  {x * 3}")
print("\n")

# division
print(f"division :  {x / 3}")
print("\n")

# int division
print(f"int division :  {(x * 100)//3}")
print("\n")

# mod
print(f"mod :  {((x * 100)//3)%2}")
print("\n")

# power
print(f"power :  {x**2}")
print("\n")


addition : tensor([[2.3377, 2.9241, 2.6973],
        [2.4802, 2.0216, 2.5332]])


Substraction :  tensor([[-1.6623, -1.0759, -1.3027],
        [-1.5198, -1.9784, -1.4668]])


Multiplication :  tensor([[1.0131, 2.7722, 2.0919],
        [1.4405, 0.0649, 1.5995]])


division :  tensor([[0.1126, 0.3080, 0.2324],
        [0.1601, 0.0072, 0.1777]])


int division :  tensor([[11., 30., 23.],
        [16.,  0., 17.]])


mod :  tensor([[1., 0., 1.],
        [0., 0., 1.]])


power :  tensor([[1.1404e-01, 8.5390e-01, 4.8624e-01],
        [2.3057e-01, 4.6832e-04, 2.8427e-01]])




### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0705, 0.3750, 0.4663],
        [0.8754, 0.9032, 0.0810]])
tensor([[0.5711, 0.3359, 0.3449],
        [0.0623, 0.6669, 0.9232]])


In [ ]:
# add
print(a + b)
print("\n")
# sub
print(a - b)
print("\n")
# multiply
print(a * b)
print("\n")
# division
print(a / b)
print("\n")
# power
print(a ** b)
print("\n")
# mod
print(a % b)
print("\n")

tensor([[0.6416, 0.7109, 0.8111],
        [0.9377, 1.5701, 1.0042]])


tensor([[-0.5006,  0.0390,  0.1214],
        [ 0.8130,  0.2362, -0.8421]])


tensor([[0.0403, 0.1260, 0.1608],
        [0.0546, 0.6024, 0.0748]])


tensor([[ 0.1235,  1.1162,  1.3520],
        [14.0415,  1.3542,  0.0878]])


tensor([[0.2199, 0.7193, 0.7686],
        [0.9917, 0.9343, 0.0983]])


tensor([[0.0705, 0.0390, 0.1214],
        [0.0026, 0.2362, 0.0810]])




In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 5., 9.],
        [5., 3., 4.]])

In [ ]:
e = torch.randint(size=(2,3), low=2, high=5, dtype=torch.float32)
e

tensor([[4., 3., 3.],
        [3., 2., 3.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([21., 12.])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([6.0000, 4.0000, 6.5000])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(3.)

In [ ]:
# product
torch.prod(e)

tensor(18900.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.1679)

In [ ]:
# variance
torch.var(e)

tensor(4.7000)

In [ ]:
# argmax
torch.argmax(e)

tensor(2)

In [ ]:
# argmin
torch.argmin(e)

tensor(4)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[1, 1, 4],
        [4, 3, 7]])
tensor([[3, 0],
        [1, 3],
        [8, 5]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[36, 23],
        [71, 44]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[1, 4],
        [1, 3],
        [4, 7]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 9., 7.],
        [2., 6., 3.],
        [3., 0., 1.]])

In [ ]:
# determinant
torch.det(h)

tensor(-63.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.0952,  0.1429,  0.2381],
        [-0.1111,  0.3333, -0.2222],
        [ 0.2857, -0.4286,  0.2857]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[6, 4, 1],
        [8, 9, 7]])
tensor([[4, 0, 2],
        [9, 1, 0]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[9., 3., 7.],
        [6., 0., 9.]])

In [ ]:
#log
torch.log(k)

tensor([[2.1972, 1.0986, 1.9459],
        [1.7918,   -inf, 2.1972]])

In [ ]:
#exp
torch.exp(k)

tensor([[8.1031e+03, 2.0086e+01, 1.0966e+03],
        [4.0343e+02, 1.0000e+00, 8.1031e+03]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[3.0000, 1.7321, 2.6458],
        [2.4495, 0.0000, 3.0000]])

In [ ]:
#sigmod
torch.sigmoid(k)

tensor([[0.9999, 0.9526, 0.9991],
        [0.9975, 0.5000, 0.9999]])

In [ ]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.9526, 0.9526, 0.1192],
        [0.0474, 0.0474, 0.8808]])

In [ ]:
#relu
torch.relu(k)

tensor([[9., 3., 7.],
        [6., 0., 9.]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print("\n")
print(n)

tensor([[0.1490, 0.9240, 0.0914],
        [0.1895, 0.6353, 0.0506]])


tensor([[0.5627, 0.6954, 0.5880],
        [0.6326, 0.8524, 0.3640]])


In [ ]:
m.add_(n)

tensor([[0.7116, 1.6194, 0.6794],
        [0.8222, 1.4877, 0.4146]])

In [ ]:
m

tensor([[0.7116, 1.6194, 0.6794],
        [0.8222, 1.4877, 0.4146]])

In [ ]:
n

tensor([[0.5627, 0.6954, 0.5880],
        [0.6326, 0.8524, 0.3640]])

In [ ]:
torch.relu(m)

tensor([[0.7116, 1.6194, 0.6794],
        [0.8222, 1.4877, 0.4146]])

In [ ]:
m.relu_()

tensor([[0.7116, 1.6194, 0.6794],
        [0.8222, 1.4877, 0.4146]])

In [ ]:
m

tensor([[0.7116, 1.6194, 0.6794],
        [0.8222, 1.4877, 0.4146]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)

In [ ]:
a

tensor([[0.5144, 0.7377, 0.8827],
        [0.6704, 0.8591, 0.4949]])

In [ ]:
 b = a

In [ ]:
b

tensor([[0.5144, 0.7377, 0.8827],
        [0.6704, 0.8591, 0.4949]])

In [ ]:
a[0][0]

tensor(0.5144)

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.7377, 0.8827],
        [0.6704, 0.8591, 0.4949]])

In [ ]:
b

tensor([[0.0000, 0.7377, 0.8827],
        [0.6704, 0.8591, 0.4949]])

In [ ]:
id(a)

136066321867104

In [ ]:
id(b)

136066321867104

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.7377, 0.8827],
        [0.6704, 0.8591, 0.4949]])

In [ ]:
b

tensor([[0.0000, 0.7377, 0.8827],
        [0.6704, 0.8591, 0.4949]])

In [ ]:
a[0][0]

tensor(0.)

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.7377,  0.8827],
        [ 0.6704,  0.8591,  0.4949]])

In [ ]:
b

tensor([[0.0000, 0.7377, 0.8827],
        [0.6704, 0.8591, 0.4949]])

In [ ]:
id(a)

136066321867104

In [ ]:
id(b)

136063636813552

## Practice

In [ ]:
print(torch.__version__)

2.5.1+cu121


**Introducion to tensors**

Creating tensors

In [ ]:
scaler = torch.tensor(7)

In [ ]:
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item() #get tensor back as python int

7

In [ ]:
#vector
vector = torch.tensor([7,7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix

In [ ]:
matrix = torch.tensor([[7,8],[9,10]])

In [ ]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#tensor



In [ ]:
tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
#create random tensor of size (3,4)

random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.0203, 0.4975, 0.8872, 0.9519],
        [0.9643, 0.3617, 0.9293, 0.9407],
        [0.0606, 0.9037, 0.5426, 0.8716]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
#create a random tensor of size (224, 224, 3)
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor

tensor([[[0.2923, 0.6510, 0.5966],
         [0.1108, 0.0856, 0.9412],
         [0.0763, 0.4035, 0.2077],
         ...,
         [0.2865, 0.2699, 0.6691],
         [0.8953, 0.9658, 0.1482],
         [0.5646, 0.9885, 0.1290]],

        [[0.1208, 0.6051, 0.0500],
         [0.2869, 0.7851, 0.6000],
         [0.6780, 0.2589, 0.7975],
         ...,
         [0.1626, 0.2129, 0.8984],
         [0.9548, 0.3675, 0.1588],
         [0.9046, 0.2704, 0.2425]],

        [[0.9679, 0.3111, 0.3530],
         [0.9882, 0.7131, 0.3690],
         [0.5529, 0.1149, 0.9558],
         ...,
         [0.9963, 0.5664, 0.3362],
         [0.1963, 0.8287, 0.9005],
         [0.1713, 0.1787, 0.3773]],

        ...,

        [[0.6686, 0.0053, 0.4957],
         [0.0683, 0.3831, 0.5989],
         [0.4744, 0.3179, 0.4581],
         ...,
         [0.6116, 0.2511, 0.5328],
         [0.4314, 0.9411, 0.1518],
         [0.5296, 0.6937, 0.1041]],

        [[0.5925, 0.7035, 0.4390],
         [0.2245, 0.9024, 0.2381],
         [0.

In [ ]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
random_image_tensor.size

<function Tensor.size>

In [ ]:
random_image_tensor.ndim

3

In [ ]:
#create tensor of all zeros

tensor_zeros = torch.zeros(size=(2,3))
tensor_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#create tensor of all ones

tensor_ones = torch.ones(size=(3,4))
tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# create a range and tensors like

''' torch.arange(start, end, step) where start = start of range , end = end of range , step = how many steps in b/w each value '''

' torch.arange(start, end, step) where start = start of range , end = end of range , step = how many steps in b/w each value '

In [ ]:
#use torch.arange() , torch.range() is deprecated

zero_to_ten_deprecated = torch.range(0,10)

<ipython-input-41-cfbd2d232aae>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


In [ ]:
zero_to_ten_deprecated

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
zero_to_ten_deprecated = torch.range(0, 10, 2)
zero_to_ten_deprecated

<ipython-input-44-05cac08118bb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10, 2)


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
zero_to_ten = torch.arange(0,10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
zero_to_ten = torch.arange(start = 0,end= 10, step=2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
#create a tensor of zeros similar to another tensor

similar_zeros_tensor = torch.zeros_like(input = tensor_zeros)
similar_zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"device tensor is stored on : {some_tensor.device}")

tensor([[0.1062, 0.5799, 0.9391, 0.0775],
        [0.8863, 0.7358, 0.3904, 0.5745],
        [0.5659, 0.0775, 0.1389, 0.7966]])
shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
device tensor is stored on : cpu


In [ ]:
#create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor #tensor don't change unless reassigned

tensor([1, 2, 3])

In [ ]:
#muliply by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
#add and reasign

tensor = tensor + 10
tensor

tensor([20, 30, 40])

In [ ]:
tensor = tensor.add(10)
tensor

tensor([30, 40, 50])

In [ ]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
tensor.matmul(tensor)

tensor(14)

In [ ]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 2.07 ms, sys: 0 ns, total: 2.07 ms
Wall time: 2.04 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 117 µs, sys: 9 µs, total: 126 µs
Wall time: 132 µs


tensor(14)

In [ ]:
#shapes need to be in the right way
import torch

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]
                         ], dtype = torch.float32)
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]
                         ], dtype = torch.float32)

In [ ]:
torch.matmul(tensor_A, tensor_B) #we haveto make inner dimension same for this

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
print(tensor_A)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [ ]:
print(tensor_B)

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
#view tensor_A and tensor_B T(transpose)

print(tensor_A)
print("==================")
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
output = torch.matmul(tensor_A,tensor_B.T)

In [ ]:
output

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
#torch.mm is shortcut for matmul

torch.mm(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
import torch

In [ ]:
# torch.empty(size) : uninitialized
#syntax
x = torch.empty(* , dtype=None, device=None, requires_grad=False)

SyntaxError: invalid syntax (<ipython-input-3-b893d226b606>, line 3)

In [ ]:
x = torch.empty(2,3)
print(x)

tensor([[6.9488e+22, 7.1221e+28, 1.0886e+27],
        [2.9602e+29, 1.7938e+25, 1.9205e+31]])


In [ ]:
#slicing

x = torch.rand(5,3)
x

tensor([[0.2379, 0.4211, 0.7446],
        [0.6508, 0.3794, 0.9680],
        [0.3242, 0.1813, 0.6642],
        [0.8193, 0.6333, 0.6557],
        [0.4909, 0.8871, 0.2774]])

In [ ]:
print(x[:]) # all rows & all columns

tensor([[0.2379, 0.4211, 0.7446],
        [0.6508, 0.3794, 0.9680],
        [0.3242, 0.1813, 0.6642],
        [0.8193, 0.6333, 0.6557],
        [0.4909, 0.8871, 0.2774]])


In [ ]:
print(x[:,0]) # all rows, columns 0

tensor([0.2379, 0.6508, 0.3242, 0.8193, 0.4909])


In [ ]:
print(x[:,1]) # all rows, column 1

tensor([0.4211, 0.3794, 0.1813, 0.6333, 0.8871])


In [ ]:
print(x[1,:]) # row 1, all column

tensor([0.6508, 0.3794, 0.9680])


In [ ]:
print(x[1,1]) #element at 1,1

tensor(0.3794)


In [ ]:
#get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.3793500065803528


In [ ]:
#reshape with torch.view()
x = torch.rand(4,4)
x

tensor([[0.3149, 0.0394, 0.2123, 0.2415],
        [0.4906, 0.0198, 0.3771, 0.9823],
        [0.1332, 0.0292, 0.7843, 0.2983],
        [0.8152, 0.0055, 0.1631, 0.6466]])

In [ ]:
y = x.view(16)
y

tensor([0.3149, 0.0394, 0.2123, 0.2415, 0.4906, 0.0198, 0.3771, 0.9823, 0.1332,
        0.0292, 0.7843, 0.2983, 0.8152, 0.0055, 0.1631, 0.6466])

In [ ]:
# view() function is used to reshape a tensor. It allows you to create a new tensor with the same data but a different shape
x = torch.rand(4,3)
print("Original tensor: ")
print(x)

#reshape it to a tensor of shape(2,6)
y = x.view(2,6)
print("Reshaped tensor :")
print(y)

Original tensor: 
tensor([[0.2962, 0.1801, 0.0870],
        [0.0502, 0.4863, 0.7310],
        [0.6731, 0.1509, 0.1507],
        [0.1580, 0.5260, 0.7714]])
Reshaped tensor :
tensor([[0.2962, 0.1801, 0.0870, 0.0502, 0.4863, 0.7310],
        [0.6731, 0.1509, 0.1507, 0.1580, 0.5260, 0.7714]])


In [ ]:
# view() function is used to reshape a tensor. It allows you to create a new tensor with the same data but a different shape
x = torch.rand(4,3)
print("Original tensor: ")
print(x)

#reshape it to a tensor of shape(2,6)
y = x.view(-1,6)
print("Reshaped tensor :")
print(y)

Original tensor: 
tensor([[0.1152, 0.2643, 0.6295],
        [0.5788, 0.0599, 0.7099],
        [0.3957, 0.3801, 0.1549],
        [0.1380, 0.6293, 0.3892]])
Reshaped tensor :
tensor([[0.1152, 0.2643, 0.6295, 0.5788, 0.0599, 0.7099],
        [0.3957, 0.3801, 0.1549, 0.1380, 0.6293, 0.3892]])


In [ ]:
# converting a torch tensor to a numpy array and vice versa

In [ ]:
tensor = torch.ones(5)
tensor

tensor([1., 1., 1., 1., 1.])

In [ ]:
tensor_to_numpy = tensor.numpy()
tensor_to_numpy

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
#careful : if the tensor is on the CPU (not in the GPU),
# both objects will share the same memory location, so changing one
# will also change the other

In [ ]:
tensor.add_(1)
tensor

tensor([2., 2., 2., 2., 2.])

In [ ]:
tensor_to_numpy

array([2., 2., 2., 2., 2.], dtype=float32)

In [ ]:
# numpy to torch with .from_numpy()

import numpy as np

numpy_array = np.ones(5)
print("Original array :", numpy_array)

numpy_to_tensor = torch.from_numpy(numpy_array)
print("Numpy to Torch is :",numpy_to_tensor)

Original array : [1. 1. 1. 1. 1.]
Numpy to Torch is : tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
# numpy to torch with .from_numpy()

import numpy as np

numpy_array = np.ones(5)
print("Original array :", numpy_array)

numpy_to_tensor = torch.from_numpy(numpy_array)
print("original Numpy to Torch is :",numpy_to_tensor)

print("--------------------------------------------------------------------")
numpy_array += 10
print("New array after adding :", numpy_array)

numpy_to_tensor = torch.from_numpy(numpy_array)
print("New Numpy to Torch is :",numpy_to_tensor)

Original array : [1. 1. 1. 1. 1.]
original Numpy to Torch is : tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
--------------------------------------------------------------------
New array after adding : [11. 11. 11. 11. 11.]
New Numpy to Torch is : tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


In [ ]:
# by default all tensor are created on the CPU,
# but you can also move them to the GPU (only if it's available)

if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device = device)
  x = x.to(device)
  z = x + y
  # z = z.numpy() # not possible because numpy cannot handle GPU tenors
  # move to CPU again
  z.to("CPU")  # ".to" can also change dtype together!
  # z = z.numpy()

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
  print("GPU not available. Using CPU")

GPU is available!
Using GPU: Tesla T4
